### ISSUE TITLE
NSPopUpButton has an extra, black, menu item on top

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-gui#126]
![popupbug](https://user-images.githubusercontent.com/27943/147351678-d35ea6fd-c761-49e1-b495-93c2b443d76b.jpg)

Steps to reproduce:

1. Open an app that uses NSPopUpButton
2. Click on the popup button

Result: See the attached image.  There is a black menu item
Expected: The popup should appear, but not with the blank, black menu item.

**Comment by gcasa** [comment]
This is not just happening in Gorm, but in every app which uses NSPopUpButton.

**Comment by fredkiefer** [comment]
I could reproduce this behaviour. As it was you that made the last change to the file NSPopUpButtonCell.m I would recommend that you start investigation be removing that change. If this solves the issue you could go ahead by investigating further whether the change is bad or some unrelated code breaks the expected behaviour.

**Comment by gcasa** [comment]
Okay, will do.

**Comment by gcasa** [comment]
The last commit I made to NSPopUpButtonCell.m was 7023c7d06d5298f23d509bad7602569dced71b53 which was about 2 months ago.   The change was simple:

  [self setAltersStateOfSelectedItem: YES];
  [self setUsesItemFromMenu: YES];

Adding those two lines.   I have reverted the file to that commit locally, and it doesn't change the behavior.    GC

**Comment by fredkiefer** [comment]
This issue was caused by an change to NSMenuPanel for the Wayland backend. There a new method -menu was added which conflicted with the already existing NSResonder method. I sorted that out by renaming the new method to -_menu. This still needs to be adjusted in the Wayland backend. But for this specific issue things should be OK again.
