### ISSUE TITLE
bitmap format big & little endian in image representations

### ISSUE THREAD

**Issue by rmottola** [gnustep/libs-gui#267]
We should ensure we write & read the endian format property to all file types we support.
If a specific library or format do not support a specific format, byteswapping should happen before.

Most importantly TIFF is ignoring the flag

http://www.simplesystems.org/libtiff/functions/TIFFOpen.html#byte-order

Reading is automatic, writing happens native if not otherwise specified..
Question: the byte is set for file, not image. Will they all be coherent?

**Comment by fredkiefer** [comment]
I don't understand what you mean by `Most importantly TIFF is ignoring the flag`. The documentation says otherwise or at least I read it differently. But it is really questionable what the tiff library will do if we specify that value. Most likely it will still expect that the given data is in host byte order and just write it differently, when the flag is given. This won't help us.
What we should do is byte swap the data before handing it over to libtiff, when the NSBitmapFormatSixteenBitBigEndian flag is set. We also need to think about NSBitmapFormatThirtyTwoBitBigEndian for 32 bit data.

**Comment by rmottola** [comment]
@fredkiefer do you think we are done with just the TIFF fixes or are there other libraries to check?
I don't think, since support applies only to > 8bit depths and PNG is big-endian by definition and sets it, and TIFF we fixed, I don't see something else left.
