### ISSUE TITLE
Finish NSLayoutConstraints implementation

### ISSUE THREAD

**Issue by gcasa** [gnustep/libs-gui#72]
Need to figure out how to apply the constraints which are decoded.

**Comment by BennyKJohnson** [comment]
@gcasa any progress on this front? I was considering starting an implementation of the engine. My plan was to begin with a simple class to solve the equations for a given set of layout constraints, I would begin with the simplest cases and build up from there. If this was successful I would look at integrating it into the event loop.

**Comment by gcasa** [comment]
Hey.  I haven't gotten around to it as of yet.  Feel free to start an implementation!  I really don't know where to begin.

**Comment by BennyKJohnson** [comment]
@gcasa I wanted to provide an update on this. AutoLayout uses an algorithm called [Cassowary](https://constraints.cs.washington.edu/cassowary/). There are a number of existing library implementations, I chose [Kiwi](https://github.com/nucleic/kiwi) and I have written an auto layout engine that bridges NSLayoutConstraint to it. I have a number of test cases that are passing but I still have some outstanding work to do in order to support all auto layout functionality. Also I haven't looked at integrating it into the view pipeline yet because I wanted to ensure I could get the correct calculations for the constraints first.

 I will aim to push my work on the engine class soon.

**Comment by gcasa** [comment]
Hey @BennyKJohnson. This is very awesome!  I'm wondering if we have a copyright assignment/disclaimer from you.  If not would you mind signing one?   Please write me at greg.casamento@gmail.com so I have your email.

**Comment by gcasa** [comment]
The email you need to ping at the FSF is assign@gnu.org.  You need to tell them you need a copyright assignment for the gnustep project.  Thanks again!   I am really looking forward to taking a look at your code! :) @fredkiefer

**Comment by gcasa** [comment]
@BennyKJohnson I hope this didn't scare you away.  I haven't seen any activity since my last comment.

**Comment by BennyKJohnson** [comment]
@gcasa Sorry for the late response. Life got in the way and it took me a bit longer than I expected to push my work. Here is the repo with my implementation https://github.com/BennyKJohnson/GSAutoLayoutEngine.

There are a couple of issues to my work: 
- I haven't attempted to compile against GNUstep, I'm expected some changes will need to made to support it
- Memory management needs to addressed, its not something I deal with on a daily basis, I leaned on ARC to take care of the ObjC side of things
- It hasn't been integrated into the view runloop.  It only solves the alignment rect (frame) for a given view. I used unit tests heavily when working on it.
- Kiwi library wasn't a great choice for the solver backing library, it doesn't have the required granularity for the constraint priorities needed for a proper Cocoa implementation
- A lot of optimization opportunities have been left on the table for this first attempt, for example cleaning up the supporting internal constraints and variables when they are no longer required.

Next steps will be to try to compile it with GNUstep and integrate it into the view loop. 

I will try to complete the copyright assignment for you. In the meantime my implementation is unlicensed so feel free to copy it outright.

**Comment by BennyKJohnson** [comment]
Here's an update on my progress since my last update: 

- Added support for converting an NSAutoresizingMask into constraints
- Added automatic bootstrapping of auto layout into the window
- Integrated auto layout into the view runloop, updates layout when the window is resized

With this work complete, I now finally have a working end to end demo.  My demo is not super interesting, on the surface its just a view that is pinned to the top right corner of the window view however it is setup using only public auto layout methods and the layout is calculated across 3 views (root window view, window content view, color view) with each view containing 4 constraints. If you wish to give it a go you'll need to install my fork of [libsgui](https://github.com/BennyKJohnson/libs-gui/tree/autolayout-engine-integration) and download the [test project](https://github.com/BennyKJohnson/SimpleAutolayoutTest).

<img width="686" alt="Screen Shot 2022-10-29 at 7 10 27 pm" src="https://user-images.githubusercontent.com/7237725/198821175-571320db-0320-4eb8-a90c-d1005176eb7a.png">


Whats left:
- Refactor auto layout engine to no longer use the third party kiwi library and write a cassowary implementation in ObjC. 
- Implement debug autolayout methods, I'm currently blocked on this by the auto layout engine implementation and also some lack of understanding of the algorithm
- Xib integration, I know this was somewhat implemented but it was disabled, @gcasa maybe you can take another look at this?
- NSView anchor methods
- NSLayoutConstraint from visual language
- Optimising and benchmarking
- Improve intrinsic content size support for Cocoa UI elements

**Comment by gcasa** [comment]
Awesome progress!!!  Keep me informed!  I would be happy to take a look once you're done.  @fredkiefer is the authority with respect to code accepted in gui but I will give any feedback I have.

**Comment by gcasa** [comment]
Should this issue be closed, I thought this functionality was merged.

**Comment by BennyKJohnson** [comment]
Hello @gcasa, sorry for the radio silence, only the VFL parser was merged. I've got a near complete working implementation for Autolayout. The only remaining part I'm working on is the debugging functionality, but these functions are not essential and can be added in the future. One of the main problems I have is I don't know what the best way to proceed with a PR. There are various pieces of functionality like view/layout hook functionality, the auto layout engine and the cassowary engine. In total it would be several thousand lines of code. My preferred approach would be to submit the functionality from bottom to top. This would however mean that the code won't be functional until everything is merged but would still compile. I would like to hear your thoughts. 

My work can be found here https://github.com/BennyKJohnson/CassowaryKit and https://github.com/BennyKJohnson/libs-gui/tree/autolayout-engine-cassowary

**Comment by BennyKJohnson** [comment]
@gcasa @fredkiefer I have completed the implementation of all the auto layout APIs including debugging, and I am now ready to initiate the Pull Request process. However, the amount of work is significant, making it unrealistic to submit it in a single PR. I think it would be more efficient to submit it incrementally, so I'll be submitting pieces of work until everything has been submitted. This will mean that there will be source code that won't be contributing functionality until the whole work is submitted. I hope this approach is okay with you all, let me know otherwise.

**Comment by gcasa** [comment]
@BennyKJohnson reassigned this to you since you're the one working on it. :)

**Comment by gcasa** [comment]
Merged code.
