### ISSUE TITLE
Bug: NSTextField does not emit action for endsActionOnEndEditing when closing window with "OK" button

### ISSUE THREAD

**Issue by Letterus** [gnustep/libs-gui#98]
See behaviour when closing TaskEditor/TaskEditorController of https://github.com/Letterus/app-time-tracker

Fred is taking care of this. Might be something about KVO/KVB.

**Comment by fredkiefer** [comment]
I spend quite some time hunting this  one down. It turns out I had to fix three separate issues in GUI to correct this behaviour. As Ivan finally wants to release GNUstep over this weekend I will delay my commit until after the release. Having three untested changes at once is too much at this point in time.

**Comment by fredkiefer** [comment]
I committed the fixes. Please give it a try.
